"""
配置项
"""
from dataclasses import dataclass

CHUNK_SIZE = 500
CHUNK_OVERLAP = 50
CHUNK_MAX_SIZE = 1000

EMBEDDING_BATCH_SIZE = 5

ITEM_NAME_CONTEXT_CHUNK_K = 5
ITEM_NAME_CONTEXT_TOTAL_MAX_CHARS = 3000

MINERU_DOWNLOAD_TIMEOUT_SECONDS = 300
MINERU_POLL_TIMEOUT_SECONDS = 1800
MINERU_POLL_INTERVAL_SECONDS = 5
